# Generated by Django 4.1.7 on 2023-04-13 11:04

import blog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122, verbose_name='Tytuł')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Treść')),
                ('introduction', models.TextField(null=True, validators=[blog.models.validate_introduction], verbose_name='Wstęp')),
                ('background', models.ImageField(upload_to='images/post/', verbose_name='Tło wpisu')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji')),
                ('date_edited', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej edycji')),
                ('favorite', models.BooleanField(default=False, verbose_name='Czy wyróżnić post?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, validators=[blog.models.validate_category], verbose_name='Kategorie')),
                ('description', models.TextField(validators=[blog.models.validate_category_description], verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='imię')),
                ('bio', models.TextField(blank=True, default='Opis', help_text='Krótka informacja o autorze, maksymalnie 512 znaków.', validators=[blog.models.validate_bio], verbose_name='O autorze')),
                ('profile_pic', models.ImageField(default='images/profile/1.png', upload_to='images/user/', verbose_name='Zdjęcie profilowe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[blog.models.validate_content], verbose_name='Komentarz')),
                ('date_posted', models.DateTimeField(auto_now_add=True, verbose_name='Data publikacji')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Wpis')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(help_text='Wyświetlą się maksymalnie trzy kategorie.<br/> <br/>', max_length=256, to='blog.category', verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text='Krótka informacja o autorze, maksymalnie 512 znaków.', validators=[blog.models.validate_bio], verbose_name='O autorze')),
                ('profile_pic', models.ImageField(upload_to='images/profile/', verbose_name='Zdjęcie profilowe')),
                ('author_quote', models.TextField(help_text='Krótkie motto autora, maksymalnie 128 znaków.', validators=[blog.models.validate_author_quote], verbose_name='Cytat autora')),
                ('author_function', models.TextField(help_text='Nazwa funkcji jaką pełni autor.', validators=[blog.models.validate_author_function], verbose_name='Stanowisko autora')),
                ('author_url', models.URLField(blank=True, null=True, verbose_name='URL do strony użytkowanika')),
                ('pinterest_url', models.URLField(blank=True, null=True, validators=[blog.models.validate_pinterest], verbose_name='URL do Pinteresta')),
                ('facebook_url', models.URLField(blank=True, null=True, validators=[blog.models.validate_facebook], verbose_name='URL do Facebooka')),
                ('twitter_url', models.URLField(blank=True, null=True, validators=[blog.models.validate_twitter], verbose_name='URL do Twittera')),
                ('instagram_url', models.URLField(blank=True, null=True, validators=[blog.models.validate_instagram], verbose_name='URL do Instagrama')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
