# Generated by Django 4.1.4 on 2023-01-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Czy wyróżnić post?'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=122, verbose_name='Tytuł'),
        ),
        migrations.DeleteModel(
            name='FavoriteBlog',
        ),
    ]
