# Generated by Django 4.1.7 on 2023-06-16 21:07

import ckeditor.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='PL', unique=True, verbose_name='Numer telefonu')),
                ('experience', models.TextField(verbose_name='Doświadczenie')),
                ('sample_article', ckeditor.fields.RichTextField(verbose_name='Przykładowy artykuł')),
                ('accept_terms', models.BooleanField(default=False, verbose_name='Akceptuję regulamin')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
        ),
    ]
