# Generated by Django 4.1.7 on 2023-06-16 22:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articleauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleauthor',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Zatwierdzenie zgłoszenia'),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='Odrzucenie zgłoszenia'),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='blog.user', verbose_name='Użytkownik'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='experience',
            field=models.TextField(verbose_name='Doświadczenie związane z tematyką banknotów'),
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='sample_article',
            field=ckeditor.fields.RichTextField(verbose_name='Próbny artykuł'),
        ),
    ]
