# Generated by Django 4.1.7 on 2023-04-13 11:49

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(help_text='Krótka informacja o użytkowniku, maksymalnie 512 znaków.', validators=[blog.models.validate_bio], verbose_name='Bio'),
        ),
    ]
