# Generated by Django 4.1.7 on 2023-06-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articleauthor_approved_articleauthor_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleauthor',
            name='user',
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='sample_article',
            field=models.TextField(verbose_name='Próbny artykuł'),
        ),
    ]
