# Generated by Django 4.1.7 on 2023-03-23 17:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_categories_catslist_alter_catslist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, validators=[blog.models.validate_category], verbose_name='Kategoria')),
                ('description', models.TextField(validators=[blog.models.validate_category_description], verbose_name='Opis')),
            ],
        ),
        migrations.DeleteModel(
            name='CatsList',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(max_length=256, to='blog.category', verbose_name='Kategoria'),
        ),
    ]
