# Generated by Django 4.1.7 on 2023-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articleauthor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skipped_articles',
            field=models.ManyToManyField(blank=True, related_name='skipped_by', to='blog.blog', verbose_name='Skipped Articles'),
        ),
    ]
