# Generated by Django 4.1.7 on 2023-04-13 12:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Krótka informacja o użytkowniku, maksymalnie 512 znaków.', validators=[blog.models.validate_bio], verbose_name='Bio'),
        ),
    ]
