# Generated by Django 4.1.7 on 2023-06-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_skippedarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkippedArticle',
        ),
    ]
