# Generated by Django 4.1.7 on 2023-06-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_skippedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skipped_articles',
        ),
    ]
