# Generated by Django 4.1.7 on 2023-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_user_skipped_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opened_posts',
            field=models.ManyToManyField(blank=True, related_name='opened_by_users', to='blog.blog', verbose_name='Otwarte posty'),
        ),
    ]
