# Generated by Django 4.1.7 on 2023-07-08 22:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_user_can_be_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publiction_status',
            field=models.BooleanField(default=False, verbose_name='Czy opublikować post?'),
        ),
        migrations.AlterField(
            model_name='articleauthor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='PL', verbose_name='Numer telefonu'),
        ),
    ]
