# Generated by Django 4.1.7 on 2023-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_developmentnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_be_author',
            field=models.BooleanField(default=False, help_text='Czy wniosek na autora został rozpatrzony pozytywnie.', verbose_name='Czy może być autorem'),
        ),
    ]
