# Generated by Django 4.1.7 on 2023-08-16 19:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_user_can_be_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True, verbose_name='Numer telefonu'),
        ),
    ]
